version: '3'

services:
  app:
    container_name: app
    build: .
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - .:/home/node/app

  redis:
    container_name: redis
    image: redis:7.0.8-alpine